defaults: &defaults
  docker:
    - image: sgalkin/carnd-t2-dev:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |  
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .
            cmake --build .
            ctest --output-on-failure
  coverage:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Coverage .
            cmake --build .
            ctest --output-on-failure
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - build
      - coverage
